# Generated by Django 4.2.6 on 2023-10-14 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('role', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='godkendelse',
            name='Hold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poster.hold'),
        ),
    ]
