# Generated by Django 4.2.6 on 2023-10-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poster', '0003_alter_godkendelse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hold',
            name='gruppe_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='hold',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hold',
            name='role',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='opgave',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
